"""add incident triage fields

Revision ID: 370cd2caceb2
Revises: fd21a0af14af
Created: 2026-07-14 01:22:15.336892
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "370cd2caceb2"
down_revision: Union[str, None] = "fd21a0af14af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.String(length=16), nullable=False))
        batch_op.add_column(
            sa.Column("classification", sa.String(length=16), nullable=False)
        )
        batch_op.add_column(sa.Column("notes", sa.Text(), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_incidents_status"), ["status"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incidents_status"))
        batch_op.drop_column("notes")
        batch_op.drop_column("classification")
        batch_op.drop_column("status")

    # ### end Alembic commands ###
