"""initial schema

Revision ID: caa01ec29614
Revises:
Created: 2026-07-13 01:06:32.366264
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "caa01ec29614"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incidents",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("host", sa.String(length=128), nullable=False),
        sa.Column("root_guid", sa.String(length=64), nullable=False),
        sa.Column("root_image", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("detection_count", sa.Integer(), nullable=False),
        sa.Column("chain", sa.JSON(), nullable=False),
        sa.Column("techniques", sa.JSON(), nullable=False),
        sa.Column("actionable", sa.Integer(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_incidents_host"), ["host"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_incidents_last_seen"), ["last_seen"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_incidents_severity"), ["severity"], unique=False
        )

    op.create_table(
        "detections",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("attack", sa.JSON(), nullable=False),
        sa.Column("host", sa.String(length=128), nullable=False),
        sa.Column("image", sa.Text(), nullable=True),
        sa.Column("parent_image", sa.Text(), nullable=True),
        sa.Column("command_line", sa.Text(), nullable=True),
        sa.Column("process_guid", sa.String(length=64), nullable=True),
        sa.Column("incident_id", sa.String(length=32), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("matched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_event", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("detections", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_detections_host"), ["host"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_detections_incident_id"), ["incident_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_detections_matched_at"), ["matched_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_detections_rule_id"), ["rule_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_detections_severity"), ["severity"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("detections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_detections_severity"))
        batch_op.drop_index(batch_op.f("ix_detections_rule_id"))
        batch_op.drop_index(batch_op.f("ix_detections_matched_at"))
        batch_op.drop_index(batch_op.f("ix_detections_incident_id"))
        batch_op.drop_index(batch_op.f("ix_detections_host"))

    op.drop_table("detections")
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incidents_severity"))
        batch_op.drop_index(batch_op.f("ix_incidents_last_seen"))
        batch_op.drop_index(batch_op.f("ix_incidents_host"))

    op.drop_table("incidents")
    # ### end Alembic commands ###
